### ISSUE TITLE
[ENH] - Adopt  Code of conduct and enforcement procedures

### ISSUE THREAD

**Issue by trallard** [nebari-dev/governance#5]
We want to foster an inclusive, supportive and safe environment for all our community members. Need to adopt a CoC with the following:

- [ ] 1. Explicit: acceptable and unacceptable behaviour
- [ ] 2. Scope: where is this applicable
- [ ] 3. Enforcement
- [ ] 4. Reporting
- [ ] 5. Social rules
- [ ] 6. Other items that might not fit or are borderline CoC
- [ ] 7. CoC response protocol

**Comment by pavithraes** [comment]
We will primarily adapt the [Turing Way CoC](https://the-turing-way.netlify.app/community-handbook/coc.html) for Nebari. We will also include the [consequence ladder](https://github.com/mozilla/inclusion/blob/master/code-of-conduct-enforcement/consequence-ladder.md) from Mozilla's enforcement guidelines, and the [diversity statement](https://docs.scipy.org/doc/scipy/dev/conduct/code_of_conduct.html#diversity-statement) from SciPy's CoC.

**Comment by pavithraes** [comment]
@trallard I just noticed [Mozilla's license](https://github.com/mozilla/inclusion/blob/master/LICENSE) -- I'm not comfortable with it, because I think we may need to adopt the same MPL 2.0 license for a portion of Nebari. What do you think?

For now, I'll keep Turing Way's enforcement guidelines and add anything from SciPy's CoC enforcement that isn't already covered by Turin Way. Let me know if you'd like to change something here (we can also discuss changes in the PR I'll open soon!)

**Comment by trallard** [comment]
Sounds good to me
